import { Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../../api";
import type { PromptIndustry, PromptTopic } from "../../types";

export function PromptContextPicker({ disabled, onChange }: { disabled: boolean; onChange: (topics: PromptTopic[]) => void }) {
  const [industries, setIndustries] = useState<PromptIndustry[]>([]); const [chosen, setChosen] = useState<string[]>([]); const [topics, setTopics] = useState<PromptTopic[]>([]); const [selected, setSelected] = useState<PromptTopic[]>([]); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([api.listPromptIndustries(), api.getPromptSettings()]).then(([all, settings]) => { setIndustries(all); setChosen(settings.industries.map((item) => item.key)); setSelected(settings.topics); setDescription(settings.description); onChange(settings.topics); }).catch(() => undefined); }, []);
  useEffect(() => { void Promise.all(chosen.map((key) => api.listPromptTopics(key))).then((groups) => setTopics(groups.flat())).catch(() => setTopics([])); }, [chosen.join("|")]);
  const toggleIndustry = (key: string) => setChosen((items) => items.includes(key) ? items.filter((item) => item !== key) : [...items, key]);
  const toggleTopic = (topic: PromptTopic) => { const next = selected.some((item) => item.key === topic.key) ? selected.filter((item) => item.key !== topic.key) : [...selected, topic]; setSelected(next); onChange(next); };
  const grouped = useMemo(() => industries.map((industry) => ({ industry, topics: topics.filter((topic) => topic.industry_key === industry.key) })).filter((group) => chosen.includes(group.industry.key)), [industries, topics, chosen]);
  async function save() { setSaving(true); try { const result=await api.savePromptSettings({ description, industry_keys:chosen, topic_keys:selected.map((item)=>item.key) }); setSelected(result.topics); onChange(result.topics); } finally { setSaving(false); } }
  return <section className="prompt-context-card"><div className="prompt-context-heading"><Sparkles size={19}/><div><strong>Темы анализа по умолчанию</strong><small>Настройте один раз в личном профиле: можно одновременно выбрать несколько отраслей и любые темы из них.</small></div></div><textarea value={description} disabled={disabled||saving} maxLength={500} placeholder="Кратко опишите свою роль или компанию" onChange={(event)=>setDescription(event.target.value)}/><div className="prompt-topic-list">{industries.map((industry)=><button type="button" key={industry.key} disabled={disabled||saving} className={chosen.includes(industry.key)?"prompt-topic active":"prompt-topic"} onClick={()=>toggleIndustry(industry.key)}>{industry.title}</button>)}</div>{grouped.map(({industry,topics: groupTopics})=><div key={industry.key}><strong className="prompt-group-title">{industry.title}</strong><div className="prompt-topic-list">{groupTopics.map((topic)=><button type="button" key={topic.key} disabled={disabled||saving} className={selected.some((item)=>item.key===topic.key)?"prompt-topic active":"prompt-topic"} onClick={()=>toggleTopic(topic)}>{topic.title}</button>)}</div></div>)}<div className="prompt-selected">{selected.map((topic)=><span key={topic.key}>{topic.title}<button type="button" aria-label={`Убрать ${topic.title}`} onClick={()=>toggleTopic(topic)}><X size={14}/></button></span>)}</div><button type="button" className="ghost-button small" disabled={disabled||saving} onClick={()=>void save()}>{saving?"Сохраняю…":"Сохранить настройки по умолчанию"}</button></section>;
}
