import { ArrowLeft, CalendarClock, CheckCircle2, ChevronDown, ChevronRight, ChevronUp, Clock3, Search, UserRound, X, XCircle } from "lucide-react";
import { FormEvent, MouseEvent as ReactMouseEvent, useDeferredValue, useEffect, useMemo, useState } from "react";
import { api } from "../../api";
import type { AnalysisResponse, CallAction, CallActionAssignee, CallResponse, CompanyResponse, DepartmentResponse, TranscriptionResponse, TranscriptionSpeakerAssignment } from "../../types";
import { useEscapeDismiss } from "../../shared/ui/dismissible-layer";
import { TranscriptPreview } from "../../shared/ui/call";
import { DateTimePicker } from "../../shared/ui/DateTimePicker";

const statusLabels: Record<string, string> = { open: "Открыто", in_progress: "В работе", completed: "Выполнено", cancelled: "Отменено", overdue: "Просрочено" };

export function ActionsPage({ onOpen }: { onOpen: (id: string) => void }) {
  const [items, setItems] = useState<CallAction[]>([]);
  const [status, setStatus] = useState("");
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; setLoading(true); api.listActions({ status: status || undefined, q: deferredQuery.trim() || undefined, limit: 100 }).then((result) => { if (!cancelled) { setItems(result.items); setError(""); } }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Не удалось загрузить действия"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [deferredQuery, status]);
  return <section className="actions-page atmospheric-page"><header className="actions-hero glass"><div><span className="eyebrow">РАБОЧИЙ ПОТОК</span><h1>Действия</h1><p>Задачи, созданные по итогам разговоров, с ответственными и контролем срока.</p></div></header><div className="actions-toolbar glass"><label className="actions-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти действие или ответственного"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Статус действия"><option value="">Все статусы</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{error ? <div className="form-error">{error}</div> : null}<div className="actions-list glass">{loading ? <p className="actions-empty">Загружаю действия…</p> : items.length === 0 ? <p className="actions-empty">Подходящих действий пока нет.</p> : items.map((item)=><button className="action-row" type="button" key={item.id} onClick={()=>onOpen(item.id)}><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status] ?? item.status}</span><span className="action-row-main"><strong>{item.title}</strong><small>{usernameLabel(item.assignee_username)} · до {formatDateTime(item.due_at)}</small></span><ChevronRight size={18}/></button>)}</div></section>;
}

export function ActionDetailPage({ actionId, onBack, onOpenEvidence }: { actionId: string; onBack: () => void; onOpenEvidence: (action:CallAction,evidence:CallAction["evidence"][number])=>void }) {
  const [item, setItem] = useState<CallAction>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [reason, setReason] = useState("");
  useEffect(()=>{let cancelled=false;api.getAction(actionId).then((result)=>{if(!cancelled)setItem(result)}).catch((cause)=>{if(!cancelled)setError(cause instanceof Error?cause.message:"Не удалось загрузить действие")});return()=>{cancelled=true}},[actionId]);
  async function mutate(operation:"start"|"complete"|"cancel") { if(!item||busy)return;if(operation==="cancel"&&reason.trim().length<10){setError("Укажите причину отмены не короче 10 символов");return}setBusy(true);setError("");try{setItem(await api.mutateAction(item.id,operation,{expected_lock_version:item.lock_version,reason:reason.trim()}));setReason("")}catch(cause){setError(cause instanceof Error?cause.message:"Не удалось изменить действие")}finally{setBusy(false)} }
  if(error&&!item)return <section className="action-detail-page"><button className="text-button" onClick={onBack}>← К действиям</button><div className="form-error">{error}</div></section>; if(!item)return <section className="action-detail-page"><p>Загружаю действие…</p></section>;
  const terminal=item.status==="completed"||item.status==="cancelled";
  const canFinish=item.capabilities.can_complete&&!terminal;
  const canStart=item.capabilities.can_start&&item.status==="open";
  const canCancel=item.capabilities.can_cancel&&!terminal;
  return <section className="action-detail-page atmospheric-page">
    <button className="text-button action-back" type="button" onClick={onBack}><ArrowLeft size={16}/>К действиям</button>
    <header className="action-detail-head glass">
      <div className="action-detail-title"><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status]}</span><h1>{item.title}</h1>{item.description.trim() && <p>{item.description.trim()}</p>}</div>
      <aside className="action-detail-meta" aria-label="Сведения о задаче"><div><UserRound size={19}/><span><small>Ответственный</small><strong>{usernameLabel(item.assignee_username)}</strong></span></div><div><CalendarClock size={19}/><span><small>Срок выполнения</small><strong>{formatDateTime(item.due_at)}</strong></span></div></aside>
    </header>
    {error?<div className="form-error">{error}</div>:null}
    <div className="action-detail-grid">
      <section className="action-panel action-evidence-panel glass"><h2>Основание задачи</h2>{item.evidence.length===0?<p className="muted">Цитаты не приложены.</p>:item.evidence.map((e)=><blockquote key={e.id}><button className="action-evidence-link" type="button" onClick={()=>onOpenEvidence(item,e)}><p>{e.quote}</p><small>{e.speaker?`${e.speaker} · `:""}{typeof e.start_seconds==="number"?formatSeconds(e.start_seconds):"Открыть в транскрипции"}</small><span>Перейти к цитате <ChevronRight size={15}/></span></button></blockquote>)}</section>
      <section className="action-panel action-management-panel glass"><div className="action-management-heading"><div><span className="eyebrow">УПРАВЛЕНИЕ</span><h2>Статус задачи</h2></div><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status]}</span></div><div className="action-progress"><span className={item.status!=="open"?"done":"active"}>1</span><i/><span className={item.status==="completed"?"done":item.status==="in_progress"||item.status==="overdue"?"active":""}>2</span><i/><span className={item.status==="completed"?"done":""}>3</span></div><div className="action-progress-labels"><small>Открыто</small><small>В работе</small><small>Выполнено</small></div><div className="action-close-help">{item.status==="completed"?<><CheckCircle2 size={20}/><span><strong>Задача выполнена</strong><small>Дополнительных действий не требуется.</small></span></>:item.status==="cancelled"?<><XCircle size={20}/><span><strong>Задача отменена</strong><small>{item.cancel_reason||"Причина не указана"}</small></span></>:canFinish?<><CheckCircle2 size={20}/><span><strong>Как закрыть задачу?</strong><small>После фактического выполнения нажмите «Отметить выполненной».</small></span></>:<><Clock3 size={20}/><span><strong>Ожидается выполнение</strong><small>Закрыть задачу может ответственный, лидер исходного или целевого отдела либо менеджер компании.</small></span></>}</div><div className="action-controls">{canStart?<button className="ghost-button action-start-button" type="button" disabled={busy} onClick={()=>void mutate("start")}><Clock3 size={18}/>{busy?"Обновляю…":"Начать выполнение"}</button>:null}{canFinish?<button className="primary-button action-complete-button" type="button" disabled={busy} onClick={()=>void mutate("complete")}><CheckCircle2 size={18}/>{busy?"Закрываю…":"Отметить выполненной"}</button>:null}{canCancel?<div className="action-cancel-control"><label htmlFor="action-cancel-reason">Отмена задачи <small>Только если задача ошибочная или потеряла актуальность.</small></label><textarea id="action-cancel-reason" value={reason} maxLength={2000} onChange={(event)=>setReason(event.target.value)} placeholder="Укажите причину отмены — минимум 10 символов"/><button className="ghost-button danger" type="button" disabled={busy||reason.trim().length<10} onClick={()=>void mutate("cancel")}><XCircle size={17}/>Отменить задачу</button></div>:null}</div></section>
    </div>
  </section>;
}

export function CreateActionDialog({ call, analysis, transcription, speakerAssignments, companies, departments, currentUserId, onClose, onCreated }: { call: CallResponse; analysis: AnalysisResponse; transcription?: TranscriptionResponse; speakerAssignments?: TranscriptionSpeakerAssignment[]; companies: CompanyResponse[]; departments: DepartmentResponse[]; currentUserId: string; onClose:()=>void; onCreated:(action:CallAction)=>void }) {
  const companyId=call.company_uuid??""; const availableDepartments=departments.filter((d)=>d.company_uuid===companyId); const [title,setTitle]=useState(()=>nextStep(analysis)); const [description,setDescription]=useState(""); const [sourceDepartment,setSourceDepartment]=useState(call.department_uuid??availableDepartments[0]?.id??""); const [targetDepartment,setTargetDepartment]=useState(call.department_uuid??availableDepartments[0]?.id??""); const [assignee,setAssignee]=useState(""); const [assignees,setAssignees]=useState<CallActionAssignee[]>([]); const [assigneeQuery,setAssigneeQuery]=useState(""); const [assigneeResultsOpen,setAssigneeResultsOpen]=useState(false); const deferredAssigneeQuery=useDeferredValue(assigneeQuery); const [dueAt,setDueAt]=useState(""); const [quoteQuery,setQuoteQuery]=useState(""); const [fullTranscriptOpen,setFullTranscriptOpen]=useState(false); const [pendingRange,setPendingRange]=useState<{start:number;end:number}|null>(null); const [selectedRanges,setSelectedRanges]=useState<Array<{start:number;end:number}>>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEscapeDismiss(!busy, onClose);
  useEffect(()=>{if(!companyId)return;let cancelled=false;api.listActionAssignees(companyId,{q:deferredAssigneeQuery.trim()||undefined}).then((result)=>{if(!cancelled)setAssignees(result.items.filter((item)=>item.user_uuid!==currentUserId))}).catch(()=>{if(!cancelled)setAssignees([])});return()=>{cancelled=true}},[companyId,currentUserId,deferredAssigneeQuery]); const matches=useMemo(()=>findMatches(transcription?.words??[],quoteQuery),[quoteQuery,transcription?.words]);
  function chooseAssignee(user:CallActionAssignee){setAssignee(user.user_uuid);setAssigneeQuery(usernameLabel(user.username));setAssigneeResultsOpen(false);if(user.departments.length===1)setTargetDepartment(user.departments[0].id);else if(!user.departments.some((d)=>d.id===targetDepartment))setTargetDepartment("")}
  function captureTranscriptSelection(event:ReactMouseEvent<HTMLDivElement>){const selection=window.getSelection();if(!selection||selection.isCollapsed||selection.rangeCount===0){setPendingRange(null);return}const start=wordIndexFromNode(selection.anchorNode);const end=wordIndexFromNode(selection.focusNode);if(start===null||end===null||!event.currentTarget.contains(selection.anchorNode)||!event.currentTarget.contains(selection.focusNode)){setPendingRange(null);return}setPendingRange({start:Math.min(start,end),end:Math.max(start,end)})}
  function addPendingQuote(){if(!pendingRange)return;setSelectedRanges((current)=>{if(current.some((range)=>range.start===pendingRange.start&&range.end===pendingRange.end))return current;if(current.length>=20){setError("К одному действию можно добавить не более 20 цитат");return current}return[...current,pendingRange]});setPendingRange(null);window.getSelection()?.removeAllRanges()}
  function toggleQuote(range:{start:number;end:number}){setSelectedRanges((current)=>{const selected=current.some((item)=>item.start===range.start&&item.end===range.end);if(selected)return current.filter((item)=>item.start!==range.start||item.end!==range.end);if(current.length>=20){setError("К одному действию можно добавить не более 20 цитат");return current}setError("");return[...current,range]})}
  function removeQuote(range:{start:number;end:number}){setSelectedRanges((current)=>current.filter((item)=>item.start!==range.start||item.end!==range.end));if(pendingRange?.start===range.start&&pendingRange.end===range.end)setPendingRange(null)}
  async function submit(event:FormEvent){event.preventDefault();if(!analysis.id||!companyId){setError("Действия доступны только для звонков компании с готовым анализом");return}if(!dueAt){setError("Укажите срок выполнения действия");return}const effectiveAssignee=assignee||call.uploaded_by_user_uuid||"";if(!effectiveAssignee){setError("Не удалось определить ответственного: у звонка не указан загрузивший пользователь");return}setBusy(true);setError("");try{const action=await api.createAction(call.id,{analysis_uuid:analysis.id,source_department_uuid:sourceDepartment,target_department_uuid:targetDepartment,assignee_user_uuid:effectiveAssignee,title:title.trim(),description:description.trim(),due_at:new Date(dueAt).toISOString(),evidence:selectedRanges.map((range)=>({word_start_index:range.start,word_end_index:range.end}))});onCreated(action)}catch(cause){setError(cause instanceof Error?cause.message:"Не удалось создать действие")}finally{setBusy(false)}} const chosen=assignees.find((item)=>item.user_uuid===assignee);
  return <div className="action-dialog-layer" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onClose()}}>
    <form className="action-dialog glass" role="dialog" aria-modal="true" aria-labelledby="create-action-title" onSubmit={(event)=>void submit(event)}>
      <header><div><span className="eyebrow">ПО ИТОГАМ ЗВОНКА</span><h2 id="create-action-title">Создать действие</h2></div><button className="icon-button" type="button" aria-label="Закрыть" onClick={onClose}><X size={18}/></button></header>
      <label>Название<input required maxLength={200} value={title} onChange={(event)=>setTitle(event.target.value)}/></label>
      <label>Описание<textarea maxLength={10000} value={description} onChange={(event)=>setDescription(event.target.value)}/></label>
      <div className="action-form-grid"><label>Исходный отдел<select required value={sourceDepartment} onChange={(event)=>setSourceDepartment(event.target.value)}>{availableDepartments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label htmlFor="action-due-at">Срок<DateTimePicker id="action-due-at" required value={dueAt} onChange={setDueAt}/></label></div>
      <label className="action-assignee-search" onBlur={(event)=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))setAssigneeResultsOpen(false)}}>
        Ответственный
        <small className="action-field-hint">Необязательно. Если никого не выбрать, ответственным станет пользователь, загрузивший звонок.</small>
        <input value={assigneeQuery} onFocus={()=>setAssigneeResultsOpen(true)} onChange={(event)=>{setAssigneeQuery(event.target.value);setAssignee("");setAssigneeResultsOpen(true)}} placeholder="@username или имя"/>
        {assigneeResultsOpen&&!assignee?<div className="action-assignee-results">{assignees.length?assignees.map((user)=><button type="button" key={user.user_uuid} onClick={()=>chooseAssignee(user)}><strong>{usernameLabel(user.username)}</strong><small>{user.full_name} {user.full_surname}</small></button>):<small className="action-assignee-empty">Подходящих сотрудников не найдено</small>}</div>:null}
      </label>
      {chosen&&chosen.departments.length>1?<label>Целевой отдел<select required value={targetDepartment} onChange={(event)=>setTargetDepartment(event.target.value)}><option value="">Выберите отдел</option>{chosen.departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>:null}
      <fieldset className="evidence-picker">
        <legend>Цитаты из транскрипции</legend>
        <label><Search size={16}/><input value={quoteQuery} onChange={(event)=>setQuoteQuery(event.target.value)} placeholder="Поиск как Ctrl+F"/></label>
        {quoteQuery?<div className="evidence-search-results"><small>Совпадений: {matches.length}</small>{matches.slice(0,20).map((match)=><button type="button" key={`${match.start}-${match.end}`} className={selectedRanges.some((range)=>range.start===match.start&&range.end===match.end)?"selected":""} onClick={()=>toggleQuote(match)}>{(transcription?.words??[]).slice(match.start,match.end+1).map((word)=>word.text).join(" ")}</button>)}</div>:<small>Введите часть фразы и выберите нужное совпадение.</small>}
        <button className="evidence-transcript-toggle" type="button" aria-expanded={fullTranscriptOpen} onClick={()=>setFullTranscriptOpen((current)=>!current)}><span>{fullTranscriptOpen?"Скрыть полную транскрипцию":"Показать полную транскрипцию"}</span>{fullTranscriptOpen?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>
        {fullTranscriptOpen?<div className="evidence-transcript-selection"><small>Выделите мышью нужные слова в расшифровке.</small><div className="evidence-full-transcript" onMouseUp={captureTranscriptSelection}><TranscriptPreview transcription={transcription} expanded speakerAssignments={speakerAssignments} selectedEvidence={(pendingRange??selectedRanges.at(-1))?{startSeconds:transcription?.words?.[(pendingRange??selectedRanges.at(-1))!.start]?.start_seconds??0,endSeconds:transcription?.words?.[(pendingRange??selectedRanges.at(-1))!.end]?.end_seconds??undefined,wordStartIndex:(pendingRange??selectedRanges.at(-1))!.start,wordEndIndex:(pendingRange??selectedRanges.at(-1))!.end}:null}/></div>{pendingRange?<button className="primary-button evidence-add-selection" type="button" onClick={addPendingQuote}>Добавить выделенное как цитату</button>:null}</div>:null}
        {selectedRanges.length?<div className="selected-evidence-list"><div className="selected-evidence-heading"><strong>Добавленные цитаты</strong><small>{selectedRanges.length}/20</small></div>{selectedRanges.map((range,index)=><div className="selected-evidence-item" key={`${range.start}-${range.end}`}><span><small>Цитата {index+1}</small><p>{(transcription?.words??[]).slice(range.start,range.end+1).map((word)=>word.text).join(" ")}</p></span><button className="icon-button" type="button" aria-label={`Убрать цитату ${index+1}`} title="Убрать цитату" onClick={()=>removeQuote(range)}><X size={17}/></button></div>)}</div>:null}
      </fieldset>
      {error?<div className="form-error">{error}</div>:null}
      <footer><button className="ghost-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button" type="submit" disabled={busy||!targetDepartment}>{busy?"Создаю…":"Создать"}</button></footer>
    </form>
  </div>;
}

function usernameLabel(username:string){const normalized=username.trim().replace(/^@+/,"");return normalized?`@${normalized}`:""}
function wordIndexFromNode(node:Node|null){const element=node instanceof Element?node:node?.parentElement;const value=element?.closest<HTMLElement>("[data-word-index]")?.dataset.wordIndex;if(value===undefined)return null;const index=Number(value);return Number.isInteger(index)?index:null}

function findMatches(words:TranscriptionResponse["words"],raw:string){const query=raw.trim().toLocaleLowerCase("ru-RU");if(query.length<2)return[];const searchable=words.map((word,index)=>({index,text:word.text.toLocaleLowerCase("ru-RU").replace(/[^\p{L}\p{N}]+/gu,"")})).filter((word)=>word.text);const needle=query.split(/\s+/).map((token)=>token.replace(/[^\p{L}\p{N}]+/gu,"")).filter(Boolean);if(!needle.length)return[];const sentences=new Map<string,{start:number;end:number}>();for(let i=0;i<=searchable.length-needle.length;i+=1){if(!needle.every((token,index)=>searchable[i+index].text.includes(token)))continue;const sentence=sentenceRange(words,searchable[i].index,searchable[i+needle.length-1].index);sentences.set(`${sentence.start}:${sentence.end}`,sentence)}return[...sentences.values()]}
function sentenceRange(words:TranscriptionResponse["words"],matchStart:number,matchEnd:number){let start=matchStart;let end=matchEnd;while(start>0&&!endsSentence(words[start-1].text)&&sameSpeaker(words[start-1].speaker,words[start].speaker))start-=1;while(end<words.length-1&&!endsSentence(words[end].text)&&sameSpeaker(words[end].speaker,words[end+1].speaker))end+=1;return{start,end}}
function endsSentence(text:string){return/[.!?…](?:["'»”’)\]]+)?$/u.test(text.trim())}
function sameSpeaker(left?:string|null,right?:string|null){return(left??"").trim()===(right??"").trim()}
function nextStep(analysis:AnalysisResponse){const result=analysis.result_json;if(!result||typeof result!=="object"||Array.isArray(result))return"";const value=(result as Record<string,unknown>).next_step;return typeof value==="string"?value:""}
function formatDateTime(value:string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function formatSeconds(value:number){const minutes=Math.floor(value/60);return`${minutes}:${Math.floor(value%60).toString().padStart(2,"0")}`}
